### ISSUE TITLE
Sound Design

### ISSUE THREAD

**Issue by ReynoldsCahoon** [jake-pauls/Hamstars#24]
List all events that trigger sounds

- [ ] Hamster
  - [ ] Spawn
  - [ ] Running
    - [ ] Quick
    - [ ] Normal
    - [ ] Slow
  - [ ] Jumping
  - [ ] Squish
- [ ] Nuts 
  - [ ] Pickup
  - [ ] Spawn
  - [ ] Collision
  - [ ] Scoring
    - [ ] Repeat and increase pitch on multiscore?
- [ ] Ball
  - [ ] Rolling
  - [ ] Enter/Exit
  - [ ] Collision
    - [ ] Wall
    - [ ] Tube
    - [ ] Ball
- [ ] Events
  - [ ] Countdown
  - [ ] Victory
  - [ ] Game Time Warning

**Comment by Aphion** [comment]
- [ ] Running
- [ ] Jogging
- [ ] Stomping
- [ ] Jumping
- [ ] Tunnel reverb
- [ ] Nut grabbing
- [ ] Scoring nuts
- [ ] Scoring with progression
- [ ] Ball rolling
- [ ] Squish
- [ ] Nut spawn
- [ ] Nut drop
- [ ] Ball hitting Ball
- [ ] Ball hitting Wall
- [ ] Ball hitting tube
- [ ] Countdown

**Comment by ReynoldsCahoon** [comment]
- [ ] Events
  - [ ] Countdown
  - [x] Victory
  - [ ] Game Time Warning

**Comment by Aphion** [comment]
- [ ] Hamster
  - [ ] Running
    - [ ] Quick
    - [ ] Normal
    - [ ] Slow
  - [ ] Jumping
  - [ ] Squish
- [ ] Nuts 
  - [ ] Pickup
  - [ ] Spawn
  - [ ] Collision
  - [ ] Scoring
    - [ ] Repeat and increase pitch on multiscore?
- [ ] Ball
  - [ ] Rolling
  - [X] Enter/Exit
  - [ ] Collision
    - [ ] Wall
    - [ ] Tube
    - [ ] Ball
- [ ] Events
  - [ ] Countdown
  - [x] Victory
  - [ ] Game Time Warning
