### ISSUE TITLE
Improve peanut spitting

### ISSUE THREAD

**Issue by ReynoldsCahoon** [jake-pauls/Hamstars#50]
Peanuts are currently placed at the same point from the player in a static orientation. A method of 'spitting' the peanuts would resolve this, and could be used both when players drop a peanut, and when a player is squished by a hamster ball.

Drop a peanut - 'spit' a peanut directly in front of the hamster, with as little force as is required to get them out of pickup range.
Squish a hamster - 'spit' all peanuts directly in front of hamster, with great directional force.

**Comment by Kabug** [comment]
Also dropping a peanut doesn't actually update your speed at the moment so if you eat too mnay nuts and drop them all, even if you have 0 nuts left you're slow af

**Comment by ReynoldsCahoon** [comment]
@Kabug I did notice that during the test!

**Comment by Kabug** [comment]
Don't in latest merge
